### PR TITLE
Obfuscator

### PR DESCRIPTION
**Pull request by HopperElec**
Closes https://github.com/mlomb/chat-analytics/issues/81

### CODE REVIEW

**Comment by HopperElec** [comment]
Oh, I accidentally included my other PR in this one, causing the check to fail. I'll revert this shortly

**Comment by HopperElec** [comment]
The relevant URL is https://pr-82.chat-analytics.pages.dev/obfuscate

**Comment by HopperElec** [comment]
Why did it make a new commit for me merging your change... 😕

**Comment by HopperElec** [comment]
Oh, I was meant to rebase, not merge🤦‍♂️

**Comment by HopperElec** [comment]
The preview is supposed to be very trimmed, but I was trimming it based on lines and JSON is obfuscated onto one line. Since it is probably better to download it as one line (so that it is a smaller file size, which is useful since people obfuscating are likely planning on sharing the file online) and it seems strange for the preview and file to be stringified separately, I'm just going to make it also trim on characters, but in future it could be good to display JSON as a tree (like how it is displayed in the console tab of the browser developer tools)

**Comment by HopperElec** [comment]
mlomb DMd me to let me know that, when generating a report using an obfuscated export, every user is labelled as the last user. This seems strange, because I can see that the obfuscated report contains multiple users ("User 1", "User 2", "User 3"...). However, the issue is because the obfuscater uses the same obfuscation for the ID of every user (123456789123456780) meaning the report generator treats them all as the same user. The reason it is the _last_ username being displayed is due to a recent update which makes the report use the latest (most up-to-date) username for a given user (since someone could upload two reports where one is outdated and has an old username). What I'll probably do is replace `is_user_name` with something like `obfuscation_func` which is a func that takes an internal user ID (number where 1 is the first user to speak) and generates a value. For usernames, this could just be `id => "User "+id`, then for IDs it could just be `id => 123456789123456780+id`

**Comment by mlomb** [comment]
Hey!! I think the first version of this is ready. Hopefully this will help with #85

I rewrote most of the code, I was not convinced with the `JSON_PLATFORMS_PATHS` thing.
About the IDs, now a reference is kept for each entity. For each kind of entity, we create a new sequential id. If the entity is seen again, the previous ID is used, to keep the references intact.
Also, instead of hardcoding values for each field, I used [faker](https://fakerjs.dev/) to generate fake data.
I only implemented Discord and Telegram, but I doubt we will need the other platforms for now.
Also I renamed "Obfuscater" to "Obfuscator" it was a typo 😉

There is no risk merging this so I'll go for it

**Comment by HopperElec** [comment]
> I rewrote most of the code, I was not convinced with the JSON_PLATFORMS_PATHS thing.

Nor was I and I wrote it lmao, dw

**Pull request merged**
