### PR TITLE
Support for Guilds (and multiple of them)

### LINKED ISSUE #9: [Discord][Feature request] Show guild name next to channel name when multiple guilds are included in the report
I understand most users of chat-analytics are using it for researching an individual guild they own, but it is also really useful for people interested in researching themselves across guilds (the quantified self). Since this means including several guilds in the report, often which use many similar channel names (general, off-topic, vc-chat, chat-1, chat-2...), it can be hard to differentiate between some channels. If a user includes multiple guilds in a report, it would be useful to show the guild's name next to any listed channel names .

### PR DESCRIPTION
**Pull request by mlomb**
We would like to store guild data from Discord exports and include the guild concept in other platforms

Should fix #9 and then we can work in #12.

### CODE REVIEW

**Comment by HopperElec** [comment]
I know this hasn't been merged yet, so some of these will already be planned, but just in case some aren't I'll list the things I've noticed so far that might be worth doing:
- Instead of just showing the Discord logo when there are multiple chats, you could show a few (maybe the top 3) of the guild's icons stacked on top of them. For example, if the icons of my top 3 guilds were these:
hopperelec icon Demonetized SMP icon Team Poke Kippster icon
It might show them like this
Example of above icons overlaid on each other
- DMs and GCs are technically in a guild called 'Direct Messages' but they have their own icons associated with them (profile pictures of the involved users OR the GC icon) which is currently being replaced by the default Discord icon. It may be worth having a per-channel icon. If added ONTOP OF the guild icon, this could also be used to indicate the type of channel, for example a voice channel (you can send text messages in voice channels now), thread, announcements or just the hashtag for a text channel.
- The report icon is currently always shown as the initials of the guild name, but this should be the guild icon if available
- Initials do not scale. Even just two initials don't fit properly, but Discord scales them up fit up to 11

**Comment by HopperElec** [comment]
https://github.com/mlomb/chat-analytics/pull/39/commits/8dd6306e1299d7624fa092b770afe3977b7bad5d#diff-17ea9fcb0494c19a66704fa349d7d08f2f59ac34e3f5a87d4b035ad44143d763R26-R36 Why is twoOrMoreGuildsPresent not just integrated directly in the if expression? Is it going to be referenced elsewhere?

**Comment by mlomb** [comment]
> Why is `twoOrMoreGuildsPresent` not just integrated directly in the if expression? Is it going to be referenced elsewhere? [8dd6306#diff-17ea9fcb0494c19a66704fa349d7d08f2f59ac34e3f5a87d4b035ad44143d763R26-R36](https://github.com/mlomb/chat-analytics/commit/8dd6306e1299d7624fa092b770afe3977b7bad5d#diff-17ea9fcb0494c19a66704fa349d7d08f2f59ac34e3f5a87d4b035ad44143d763R26-R36)

I think it's clearer. That specific check will probably change later tho

**Comment by mlomb** [comment]
I think we are ready to merge this!

**Comment by HopperElec** [comment]
Not sure if this should be part of this PR or if it should be done separately afterwards, but I think there's been enough significant changes at this point that the demo should really be updated. I've mentioned allowing contributors to update it in issue https://github.com/mlomb/chat-analytics/issues/31 but until such a thing exists it should be updated to at least reflect most of the recent major changes

**Comment by mlomb** [comment]
I know, but I'll wait a bit longer to update it. Ideally it should be generated at build time

I've tested this PR with a lot of combinations and everything was right, I think it is time to merge.
The only thing remaining would be to fit the characters correctly in TextAvatar, but I will leave it as is for now.

**Pull request merged**
