### PR TITLE
Calls support

### PR DESCRIPTION
**Pull request by mlomb**
Hopefully implement #76 😄

### CODE REVIEW

**Comment by Laiteux** [comment]
Crashes for me

msedge_IUaym8qMFr

**Comment by mlomb** [comment]
Couldn't wait heh! It's not ready yet!
Though it shouldn't have crashed

**Comment by Laiteux** [comment]
Oops 😙

**Comment by mlomb** [comment]
Could you check it out again? Added a log that could be related with #85.

**Comment by Laiteux** [comment]
Where? I don't see much

https://github.com/mlomb/chat-analytics/assets/33204743/0fc60735-aa8e-4aa8-a2cf-81710532a239

**Comment by mlomb** [comment]
Try the one with calls 🤔

I added the following:
https://github.com/mlomb/chat-analytics/blob/509e7f855467bc97fbab553b8da9a61dbff92bd3/pipeline/process/DatabaseBuilder.ts#L426-L432

Hope it throws

**Comment by Laiteux** [comment]
Yep, that's where I am already

**Comment by Laiteux** [comment]
Firefox (thought it could be a cache issue, is it?)

upl3gfF4Ly

**Comment by Laiteux** [comment]
msedge_27RzcRFOJN

**Comment by mlomb** [comment]
@Laiteux Does the same file works in the deployed app? (https://chatanalytics.app)

**Comment by Laiteux** [comment]
It works, however I see no call stats at all, despite my JSON file containing `messages` of `type` `Call`

**Comment by mlomb** [comment]
Its not processing even one message, it can't find the channel information. Can you show me the header of the file? (scramble the sensitive information) It should look like this:

```json
{
  "guild": {
    "id": "253601524398293010",
    "name": "DefleMask",
    "iconUrl": "https://cdn.discordapp.com/icons/253601524398293010/a_801de7dbf6c4b24d8c2c0b576c36150a.png"
  },
  "channel": {
    "id": "253601524398293010",
    "type": "GuildTextChat",
    "categoryId": "497802346320101387",
    "category": "Chat",
    "name": "general-chiptune",
    "topic": "discuss chiptune stuff here"
  },
  "dateRange": {
    "after": null,
    "before": null
  },
  "messages": [...]
}
```

**Comment by Laiteux** [comment]
> Can you show me the header of the file?

Code_rOJi66Jtfc

> This PR is not merged in production yet! However if this PR breaks something that already works I can't merge

My bad. High.

**Comment by mlomb** [comment]
I can't find any reason why it does not work. The format of your file is as expected. I tried replacing the start of a file of mine with yours and it works.

**Do you have any other file that breaks?** Or this is the only one? (https://pr-88.chat-analytics.pages.dev)

Relevant code is here:

https://github.com/mlomb/chat-analytics/blob/110ce1ce9d54aded27c0ab71a471d03f6c3e4720/pipeline/parse/parsers/DiscordParser.ts#L27-L77

**Comment by Laiteux** [comment]
Sent you the file via [email](mailto:to@mlomb.me) as it contains nothing too private. Mostly calls.

**Comment by mlomb** [comment]
I tried it in the production version (https://chatanalytics.app) and in the PR (https://pr-88.chat-analytics.pages.dev) and it works as expected 🙃

Can you try again? What browser and OS are you using?

**Comment by Laiteux** [comment]
Weird. I did Ctrl+F5 before but maybe that wasn't enough. I'm on Windows, MS Edge.

**Comment by Laiteux** [comment]
Tried on Firefox, same error, uh

**Comment by Laiteux** [comment]
Ok, now it worked. Cache issues.

**Comment by Laiteux** [comment]
Woah. Could you maybe verify that this is a true stat, with my file? Seems high af 😄 

msedge_MkLYe5q3aI

**Comment by mlomb** [comment]
Checking

**Comment by mlomb** [comment]
Numbers seem correct.

Duration of calls March 2022:
```json
[3, 4, 5, 7, 39, 52, 64, 113, 301, 301, 566, 1353, 1367, 1766, 2445, 2755, 5699, 8188, 8462, 10042, 12084, 12571, 20271, 37159, 43354, 48706, 49557, 49590, 49741, 50340, 52195, 53363, 53620, 53695, 55755, 55896, 55986, 57040, 57166, 59029, 60268, 62407, 64909, 65958, 67007]
```
sum = 1291199 ~= 14.94 days

-----

I made the "Time spent on" more accurate, now it spreads the duration between days , weeks and months (and not only at the start time)
Though the plot should look very similar.

**Comment by Laiteux** [comment]
Indeed, nice. Thanks for checking too! (:

**Comment by Laiteux** [comment]
gg

**Pull request merged**
