### PR TITLE
Replaced URL regex with the one used by Discord

### PR DESCRIPTION
**Pull request by hopperelec**
This regex is simpler and more lenient, and will perfectly match anything highlighted blue within Discord (some other platforms seem to be even more lenient than this, not even requiring http(s), which seems a bit over-the-top)

Fixes https://github.com/mlomb/chat-analytics/issues/71#issuecomment-1485946551

### CODE REVIEW

**Comment by HopperElec** [comment]
I'm confused why the code coverage changes so much, or even at all?

**Comment by mlomb** [comment]
I'm not sure why the coverage did that 🤔
We should add tests to be sure the regex is working properly and to prevent regressions in the future. I'll add some later

**Comment by mlomb** [comment]
It seems that the branch was in an old commit, I merged main to the PR. It should fix the coverage issue

**Comment by HopperElec** [comment]
Ohh, I updated the Git branch in my IDE, but forgot that it was fetching it from my fork of it which I hadn't synced on GitHub

**Comment by mlomb** [comment]
I added a few tests, we can merge this :)

**Pull request merged**
